create database Quiz_Questions;

-- Use the quiz_questions database
USE quiz_questions;

-- Step 3: Create the Questions Table
CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question_text VARCHAR(255) NOT NULL,
    option1 VARCHAR(100) NOT NULL,
    option2 VARCHAR(100) NOT NULL,
    option3 VARCHAR(100),
    option4 VARCHAR(100),
    correct_answer VARCHAR(100) NOT NULL,
    category VARCHAR(50) DEFAULT 'General'
);

-- Insert sample questions into the questions table
INSERT INTO questions (question_text, option1, option2, option3, option4, correct_answer, category)
VALUES 
    ("What is the capital of France?", "Paris", "Berlin", "Rome", "Madrid", "Paris", "Geography"),
    ("Which planet is known as the Red Planet?", "Earth", "Mars", "Jupiter", "Venus", "Mars", "Science"),
    ("What is 5 + 7?", "10", "11", "12", "13", "12", "Mathematics"),
    ("Who wrote 'To Kill a Mockingbird'?", "Harper Lee", "Mark Twain", "J.K. Rowling", "Ernest Hemingway", "Harper Lee", "Literature"),
    ("Which element has the chemical symbol 'O'?", "Gold", "Oxygen", "Osmium", "Oganesson", "Oxygen", "Science");

INSERT INTO questions (question_text, option1, option2, option3, option4, correct_answer, category)
VALUES 
	-- adding geography questions 
	("What is the largest desert in the world?", "Sahara", "Arctic", "Antarctic", "Gobi", "Antarctic", "Geography"),
    ("Which country has the most natural lakes?", "Canada", "USA", "India", "Brazil", "Canada", "Geography"),
    ("What is the longest river in the world?", "Amazon", "Nile", "Yangtze", "Mississippi", "Nile", "Geography"),
    ("Which country is known as the Land of the Rising Sun?", "China", "South Korea", "Japan", "Vietnam", "Japan", "Geography"),
    ("What is the smallest country in the world?", "Monaco", "San Marino", "Vatican City", "Liechtenstein", "Vatican City", "Geography"),
    ("Which city is known as the Big Apple?", "Los Angeles", "Chicago", "New York", "Miami", "New York", "Geography"),
    ("What is the highest waterfall in the world?", "Niagara Falls", "Victoria Falls", "Angel Falls", "Yosemite Falls", "Angel Falls", "Geography"),
    ("Which continent is known as the Dark Continent?", "Asia", "South America", "Africa", "Australia", "Africa", "Geography"),
    ("Which US state is the largest by area?", "Texas", "California", "Alaska", "Montana", "Alaska", "Geography"),
    ("What is the capital of India?", "New Delhi", "Mumbai", "Kolkata", "Chennai", "New Delhi", "Geography"),
    ("Which is the longest river in India?", "Ganga", "Yamuna", "Godavari", "Brahmaputra", "Ganga", "Geography"),
    ("What is the largest desert in India?", "Thar Desert", "Rann of Kutch", "Sahara Desert", "Deosai Desert", "Thar Desert", "Geography"),
    ("Which state in India has the largest area?", "Rajasthan", "Uttar Pradesh", "Madhya Pradesh", "Maharashtra", "Rajasthan", "Geography"),
    ("What is the primary source of the river Ganga?", "Gangotri Glacier", "Yamunotri Glacier", "Kundalini Glacier", "Satopanth Glacier", "Gangotri Glacier", "Geography"),
    ("Which is the highest peak in India?", "Kangchenjunga", "Mount Everest", "K2", "Nanda Devi", "Kangchenjunga", "Geography"),
    ("The Sunderbans mangrove forest is located in which state?", "West Bengal", "Odisha", "Andhra Pradesh", "Tamil Nadu", "West Bengal", "Geography"),
    ("What is the name of the largest saltwater lake in India?", "Chilika Lake", "Vembanad Lake", "Sambhar Lake", "Loktak Lake", "Sambhar Lake", "Geography"),
    ("Which country has the longest coastline in the world?", "Canada", "Australia", "Russia", "India", "Canada", "Geography"),
    ("What is the capital of Assam?", "Guwahati", "Dispur", "Shillong", "Imphal", "Dispur", "Geography"),
    ("Which is the highest mountain peak in the world?", "Mount Kilimanjaro", "Mount Everest", "K2", "Mount Fuji", "Mount Everest", "Geography"),
    ("What is the capital of Australia?", "Sydney", "Melbourne", "Canberra", "Perth", "Canberra", "Geography"),
    ("Which is the largest island in the world?", "Greenland", "Madagascar", "Borneo", "Sri Lanka", "Greenland", "Geography"),
    ("What is the capital of Brazil?", "Rio de Janeiro", "Sao Paulo", "Brasilia", "Salvador", "Brasilia", "Geography"),
    ("Which is the largest country in the world by area?", "China", "USA", "Russia", "Canada", "Russia", "Geography"),
    ("What is the capital of South Africa?", "Johannesburg", "Cape Town", "Pretoria", "Durban", "Pretoria", "Geography"),
    -- adding science questions 👇
    ("What is the largest planet in our solar system?", "Earth", "Mars", "Jupiter", "Saturn", "Jupiter", "Science"),
    ("What do we call the change of water into vapor?", "Condensation", "Evaporation", "Precipitation", "Freezing", "Evaporation", "Science"),
    ("What is the chemical symbol for gold?", "Go", "Gd", "Ga", "Au", "Au", "Science"),
    ("What is the most abundant gas in Earth's atmosphere?", "Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen", "Nitrogen", "Science"),
    ("What is the speed of light?", "300,000 km/s", "150,000 km/s", "299,792 km/s", "299,999 km/s", "299,792 km/s", "Science"),
    ("What planet is closest to the sun?", "Venus", "Earth", "Mercury", "Mars", "Mercury", "Science"),
    ("What is the powerhouse of the cell?", "Nucleus", "Ribosome", "Mitochondria", "Chloroplast", "Mitochondria", "Science"),
    ("What is the chemical formula for water?", "H2O", "O2", "H2", "CO2", "H2O", "Science"),
    ("Who developed the theory of relativity?", "Isaac Newton", "Galileo Galilei", "Albert Einstein", "Nikola Tesla", "Albert Einstein", "Science"),
    ("What is the main gas found in the air we breathe?", "Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen", "Nitrogen", "Science"),
    ("Which planet has the most moons?", "Earth", "Jupiter", "Saturn", "Mars", "Saturn", "Science"),
    ("What is the chemical formula of water?", "H2O", "O2", "CO2", "H2", "H2O", "Science"),
    ("What is the unit of force?", "Newton", "Joule", "Watt", "Pascal", "Newton", "Science"),
    ("What is the process by which plants make their own food?", "Photosynthesis", "Respiration", "Transpiration", "Digestion", "Photosynthesis", "Science"),
    ("Which gas is essential for respiration?", "Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen", "Oxygen", "Science"),
    ("What is the atomic number of carbon?", "6", "8", "12", "14", "6", "Science"),
    ("Which of the following is a non-renewable source of energy?", "Solar", "Wind", "Coal", "Biomass", "Coal", "Science"),
    ("What is the pH value of pure water?", "7", "0", "14", "10", "7", "Science"),
    ("Which part of the human brain controls balance?", "Cerebellum", "Cerebrum", "Medulla", "Hypothalamus", "Cerebellum", "Science"),
    ("What is the formula for calculating speed?", "Speed = Distance/Time", "Speed = Time/Distance", "Speed = Distance x Time", "Speed = Distance + Time", "Speed = Distance/Time", "Science"),
    ("Which of the following is a characteristic of a magnet?", "Attracts all metals", "Attracts only iron", "Repels all metals", "Attracts wood", "Attracts only iron", "Science"),
    ("What is the chemical symbol for iron?", "Ir", "Fe", "In", "Au", "Fe", "Science"),
    ("What is the chemical symbol for silver?", "Si", "Ag", "Au", "Sr", "Ag", "Science"),
    ("What is the chemical symbol for sodium?", "So", "Na", "No", "Ni", "Na", "Science"),
    ("What is the chemical symbol for potassium?", "Po", "Pa", "K", "P", "K", "Science"),
    ("What is the chemical symbol for calcium?", "Ca", "Co", "Ce", "Cl", "Ca", "Science"),
    ("What is the chemical symbol for magnesium?", "Mg", "Ma", "Me", "Mo", "Mg", "Science"),
    ("What is the chemical symbol for copper?", "Cu", "Co", "Cp", "Cn", "Cu", "Science"),
    ("What is the chemical symbol for zinc?", "Zn", "Zi", "Za", "Zo", "Zn", "Science"),
    -- adding math questions 👇
    ("What is 15 + 9?", "23", "24", "22", "25", "24", "Mathematics"),
    ("What is the value of pi?", "3.14", "3.15", "3.13", "3.16", "3.14", "Mathematics"),
    ("What is the square root of 64?", "6", "7", "8", "9", "8", "Mathematics"),
    ("What is 9 x 8?", "71", "72", "73", "74", "72", "Mathematics"),
    ("What is 100 / 4?", "25", "24", "26", "23", "25", "Mathematics"),
    ("What is the result of 6 cubed?", "216", "126", "136", "226", "216", "Mathematics"),
    ("What is the value of 12^2?", "144", "124", "134", "154", "144", "Mathematics"),
    ("What is the smallest prime number?", "0", "1", "2", "3", "2", "Mathematics"),
    ("What is 11 x 11?", "111", "121", "131", "141", "121", "Mathematics"),
    ("What is 2 + 3?", "4", "5", "6", "7", "5", "Mathematics"),
    ("What is 10 - 4?", "5", "6", "7", "8", "6", "Mathematics"),
    ("How many sides does a triangle have?", "3", "4", "5", "6", "3", "Mathematics"),
    ("What is 4 + 4?", "7", "8", "9", "10", "8", "Mathematics"),
    ("What is 5 - 2?", "3", "4", "5", "6", "3", "Mathematics"),
    ("What comes after 9?", "8", "10", "11", "12", "10", "Mathematics"),
    ("What is 6 + 3?", "8", "9", "10", "11", "9", "Mathematics"),
    ("How many days are in a week?", "5", "6", "7", "8", "7", "Mathematics"),
    ("What is 3 + 2?", "4", "5", "6", "7", "5", "Mathematics"),
    ("What number comes before 10?", "8", "9", "11", "12", "9", "Mathematics"),
    ("What is 3 + 22?", "24", "35", "24", "25", "25", "Mathematics"),
    ("What number comes after 90?", "91", "29", "131", "122", "91", "Mathematics"),
    ("What is 7 + 8?", "14", "15", "16", "17", "15", "Mathematics"),
    ("What is 9 - 3?", "5", "6", "7", "8", "6", "Mathematics"),
    ("What is 4 x 5?", "18", "19", "20", "21", "20", "Mathematics"),
    ("What is 6 x 6?", "36", "37", "38", "39", "36", "Mathematics"),
    -- adding literature questions 
    ("Who wrote 'Pride and Prejudice'?", "Jane Austen", "Emily Bronte", "Mark Twain", "Charles Dickens", "Jane Austen", "Literature"),
    ("Who is the author of the Harry Potter series?", "J.K. Rowling", "J.R.R. Tolkien", "George R.R. Martin", "C.S. Lewis", "J.K. Rowling", "Literature"),
    ("What is the first book of the Old Testament?", "Genesis", "Exodus", "Leviticus", "Numbers", "Genesis", "Literature"),
    ("Who wrote '1984'?", "George Orwell", "Aldous Huxley", "Ray Bradbury", "Arthur C. Clarke", "George Orwell", "Literature"),
    ("Who wrote 'The Catcher in the Rye'?", "J.D. Salinger", "Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "J.D. Salinger", "Literature"),
    ("What is the name of the hobbit played by Elijah Wood in the Lord of the Rings movies?", "Samwise", "Frodo", "Bilbo", "Pippin", "Frodo", "Literature"),
    ("Who wrote 'The Great Gatsby'?", "Ernest Hemingway", "F. Scott Fitzgerald", "William Faulkner", "John Steinbeck", "F. Scott Fitzgerald", "Literature"),
    ("Who is the author of 'Moby-Dick'?", "Herman Melville", "Mark Twain", "Nathaniel Hawthorne", "Henry James", "Herman Melville", "Literature"),
    ("Who wrote 'War and Peace'?", "Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev", "Leo Tolstoy", "Literature"),
    ("Who wrote the poem 'My Mother at Sixty-Six'?", "Kamala Das", "R. Parthasarathy", "Harivansh Rai Bachchan", "Sarojini Naidu", "Kamala Das", "Literature"),
    ("In the story 'The Last Lesson', what was the main reason for the French teacher's sadness?", "The school was closing", "The teacher was retiring", "The students were leaving", "The language was being banned", "The language was being banned", "Literature"),
    ("What does the 'mirror' symbolize in the poem 'A Photograph'?", "Memories", "Time", "Beauty", "Death", "Memories", "Literature"),
    ("In 'The Tiger King', who was the tiger king?", "Maharaja of Pratibandapuram", "Maharaja of Mysore", "Maharaja of Jaipur", "Maharaja of Jodhpur", "Maharaja of Pratibandapuram", "Literature"),
    ("What is the central theme of the poem 'Keeping Quiet'?", "Environmental protection", "Peace and introspection", "Humanity and love", "War and violence", "Peace and introspection", "Literature"),
    ("In the story 'The Enemy', who was Dr. Sadao's patient?", "A Japanese soldier", "An American soldier", "A Chinese prisoner", "A German spy", "An American soldier", "Literature"),
    ("What did the narrator of 'A Visit to Cambridge' notice about the old man?", "He was blind", "He was a famous scientist", "He was a former professor", "He was a poet", "He was blind", "Literature"),
    ("In 'The Rattrap', what does the peddler do when he receives a Christmas gift?", "He returns it", "He steals it", "He feels guilty", "He gives it to the poor", "He feels guilty", "Literature"),
    ("In the poem 'The Ballad of Puran Singh', what happens to Puran Singh at the end?", "He dies in battle", "He is rewarded for his bravery", "He is sent back to his village", "He becomes a hero", "He dies in battle", "Literature"),
    ("In 'The Portrait of a Lady', what is the relationship between the narrator and the old woman?", "Grandmother and grandson", "Mother and son", "Teacher and student", "Father and daughter", "Grandmother and grandson", "Literature"),
    ("Who is the main character in 'The Three Little Pigs'?", "Pig 1", "Pig 2", "The Wolf", "The Pigs", "The Pigs", "Literature"),
    ("What did the tortoise and the hare race for?", "A prize", "A carrot", "A house", "A crown", "A prize", "Literature"),
    ("What is the color of the sky during the day?", "Blue", "Red", "Green", "Yellow", "Blue", "Literature"),
    ("Who wrote 'The Adventures of Tom Sawyer'?", "Mark Twain", "J.K. Rowling", "Harper Lee", "Charles Dickens", "Mark Twain", "Literature"),
    ("What did the lion say to the mouse in 'The Lion and the Mouse'?", "Thank you", "I will eat you", "You are my friend", "Help me", "Help me", "Literature"),
    ("Who helps the gingerbread man escape in the story?", "A horse", "A fox", "A cow", "A chicken", "A fox", "Literature");